### ISSUE TITLE
Better .onMessage event for plugins

### ISSUE THREAD

**Issue by EhsanKia** [Jiiks/BetterDiscordApp#157]
At it is right now, it's quite a mess it seems.

The .onMessage gets somewhere between 2 to 6 calls for every message.

Most of the time, I guess people may not care, but I'm running into an issue where the message is still in the "sending" state, and my plugin only works when I work on the last mutation. Any chance they mutations can be filtered and only the very last one call the .onMessage on the plugin?

I think the main one causing trouble are the one's that contain the ".message-sending" class.

**Comment by EhsanKia** [comment]
An update to this, `.onSwitch` is also called multiple times, and again causes some problems as it is on some of my script. I'm attaching handlers inside it, and my handlers are being attached / called twice.

**Comment by megamit** [comment]
i agree that the onMessage function needs work. in the mean time i suggest using your own mutation observer. Also have you tried the [JQuery .on selector filtering](http://api.jquery.com/on/#on-events-selector-data-handler). You can tell jquery to not trigger your handler unless the element matches the selector you provide so instead of 
```javascript
$(".class .otherclass").on("click",function)
```
 do
```javascript
$(document.body).on("click",".class .otherclass",function)
```
This way you dont need to re register event listeners whenever the selected element gets reinserted.
This probably doesnt work for every use case but try it anyway.

**Comment by EhsanKia** [comment]
Yeah that's what I ended up doing in the meantime, but this is an actual bug since the Discord update. It used to be called once per new message and now it's being called multiple times.

**Comment by Jiiks** [comment]
This is old but there's now a `observer(e)` raw MutationObserver callback
