### ISSUE TITLE
Automatically update FFZ json list ? (Suggestion)

### ISSUE THREAD

**Issue by Yondaime008** [Jiiks/BetterDiscordApp#221]
I've noticed ffz had weekly update of emotes that logically can't cover everything. I know FFZ has a dedicated webservice for this, why can't the process be automated ? 
I've made my own script that updates 'emotedata_ffz.json' by channel name, however I wonder if there's a valid reason why this hasn't been already done.

**Comment by EhsanKia** [comment]
The main reason is, we swift through new emote codes.

I take care of the BTTV database, while Pohky does FFZ, so I can't speak for him,
but on my side, there's around 700 new emotes every week, and most of the
update is automatic, but I also manually filter a lot of emotes which have names
that could clash easily. Things like "Happy" or "Kanye" or other simple words
you wouldn't want as emote names.

Of course, we could let all those go through and fix them after the fact, but
that sounds like a lot more trouble, which is why we just do weekly batches,
and imo, once a week isn't that bad.
