### ISSUE TITLE
Disappearance of BetterDiscord after recent update and broken installer

### ISSUE THREAD

**Issue by ghost** [Jiiks/BetterDiscordApp#337]
[I USE DISCORDPTB]

As with every new Discord update sometimes BetterDiscord breaks for some reason, forcing the user to reinstall the plugin to make it function again. However since today's update I have found myself unable to install the plugin again. The installation crashes while moving resources to node_modules and force closes. 

This issue has been confirmed by two other users. 
Did DiscordPTB change it's file structure or something?

**Comment by JourneyOver** [comment]
Having the same issue :( crashing on moving resources to node_modules and have yet to find a work around..

**Comment by Tsunamical** [comment]
Sounds like this happens for the normal version a swell.

**Comment by Tsunamical** [comment]
Ignore my comment. I was incorrect.

**Comment by Margen67** [comment]
I am also using DiscordPTB. This crash has been happening ever 0.0.20
Reinstalling Discord doesn't help.
![bdptbinstallercrash](https://cloud.githubusercontent.com/assets/3462541/16359469/1c69ee9c-3aea-11e6-8c19-418fae60a39d.PNG)

**Comment by JourneyOver** [comment]
So I think I have found out the issue and a workaround until one of the devs of betterdiscord fixes it themselves, anyways what seems to be the issue is the "node_modules" folder for 0.0.20 is just named "modules" instead so therefor the installer for betterdiscord can't exactly extract to the folder that it wants to so it's crashing..

Current workaround which seems to be working well for me is to go into the resources folder in the discord folder and change the folder "modules" back to "node_modules" for the time being.

**Comment by DiglidiDudeNG** [comment]
Renaming the `modules` folder to `node_modules` does not work, and I get a crash at the very same step.

Gonna reinstall Discord and update on the situation.
