### ISSUE TITLE
Error ENOENT : no such file or directory, open

### ISSUE THREAD

**Issue by krovek** [Jiiks/BetterDiscordApp#35]
I have no idea why this is doing this but heres the link to the screen shot i took of the error 

https://gyazo.com/3f2948bf351de925777aece750f08c23

**Comment by Candunc** [comment]
![3f2948bf351de925777aece750f08c23](https://cloud.githubusercontent.com/assets/549161/11508704/67de3a02-9817-11e5-9bf7-6227d961c46b.png)
Reposted image onto github. I've noticed this happen on various installs, this may either be:

* BetterDiscord not saving into the %appdata% directory for whatever reason, or
* BetterDiscord not creating the BetterDiscordData directory on install nor launch, whichever is relevant.

I might submit a patch to fix this later today, since this issue is impacting more than just myself.

**Comment by Jiiks** [comment]
It should be fixed in 0.2

**Comment by xhip** [comment]
![captura de ecra 2015-12-02 as 13 40 15](https://cloud.githubusercontent.com/assets/7264722/11535266/086286ec-990b-11e5-9673-8467c0b42135.png)
Im getting this error.
Using the last version of both discord and BetterDiscordApp.

**Comment by Jiiks** [comment]
@xhip 

That was a OSX issues fixed here: https://github.com/Jiiks/BetterDiscordApp/commit/bb709a5352a4e5048a53abccc9fac1176a72beb9

I've now updated the release package so simply redownload the installer and it should be fine :)

**Comment by xhip** [comment]
@Jiiks Thanks for the fast reply, updating right now :+1:
