### ISSUE TITLE
What's going on with themes?

### ISSUE THREAD

**Issue by hairynachos** [Jiiks/BetterDiscordApp#374]
I've downloaded new themes, renamed them theme.css, uninstalled, reinstalled done just about everything I can think of, yet I can't get this feature to work.  It's been like this for a few months and I thought it was just an update issue, but I'm thinking something else is going on that I'm missing.  Most likely something obvious.  I'm just unsure what I'm not doing correctly.

**Comment by ShadowTeddy** [comment]
Themes go to: 
C:\Users\<Username>\AppData\Roaming\BetterDiscord\themes
And the themes themselves should be called:
'Themename'.theme.css
Examples:
Dark.theme.css
Best rule of thumb is to rename the theme rather than saving it as a .theme.css (confusing i know)
so if you downloaded a theme from this repo
And its called dark.css, rename it to dark.theme.css

You'll then need to restart Discord (Ctrl + R) and go into the Themes tray within the Better Discord menu (once it finishes initialising)
![image](https://cloud.githubusercontent.com/assets/21265755/18225117/66a97a4c-71e3-11e6-8f6a-d5ec8d264e5a.png)

I added a screenshot just in case your still stuck :)

**Comment by hairynachos** [comment]
Got it working, thanks.  What's odd is I thought the file name had to be test.theme.css but after seeing your screen shot it's just saying, "test.theme" actually has my themes back up and running correctly.

**Comment by The-Unnamed-Engineer** [comment]
So I installed Betterdiscord but the themes aren't showing up on the website... what happened to all the themes?

**Comment by noodlebox** [comment]
@ShadowTeddy @hairynachos The problem is that you have file extensions hidden. Search for how to disable "Hide extensions for known file types" for your version of Windows to avoid issues like this in the future. 

@The-Unnamed-Engineer Try #theme-repo on the BetterDiscord server.
