### ISSUE TITLE
Tooltips don't get cleaned up.

### ISSUE THREAD

**Issue by Mitsunee** [Jiiks/BetterDiscordApp#393]
How to:
Have one person post an emote (example: "MapleCat" via FFZ) and the other person mouseover the emote with tooltips turned on, so that a tooltip gets created showing that the emote is called MapleCat. Now the person who posted the emote has to edit the message to make the emote disappear (example: "Maple cat").

What happens: The tooltip will permanently stay on screen in all chats until discord gets restarted.

**Comment by noodlebox** [comment]
You can also cause this by hovering over an emote and switching channels with keyboard shortcuts. It's because the mouseout event to destroy the tooltip never gets triggered.

I [fixed this issue](https://github.com/noodlebox/BetterDiscordApp), at least two months ago, but @Jiiks doesn't seem to be accepting pull requests.

**Comment by noodlebox** [comment]
Here's a plugin that implements the fixed emote parsing, which should fix your issue:
https://github.com/noodlebox/betterdiscord-plugins/blob/master/KawaiiEmotes.plugin.js
