### ISSUE TITLE
Minimal mode cuts off server member list

### ISSUE THREAD

**Issue by Juicysteak117** [Jiiks/BetterDiscordApp#470]
Reopening issue that still exists, copy pasting old issue:

When using minimal mode the bottom 4 offline people(out of 17 total on this server)get cut off despite enough space. In the image attached, on the left side is what I see with minimal mode on, at the default size of discord. On the right side is when I attempt to scroll down on this list(the scroll bar hardly moves), to where it flashes the correct number of users for a split second where I was lucky enough to get the screenshot. The blacked at names are what is there normally, the red names are the ones that briefly show. The blue at the bottom is the window on below Discord, notice the vast extra space. If I maximize Discord, the issue is solved. This is on Windows 8.1 with the July 11th Discord update, and BetterDiscord version 0.2.8. [[Still affects BD a year later now.]]

![39122fbc-4fbe-11e6-8920-c7a7076083a7](https://cloud.githubusercontent.com/assets/20595808/25748058/976e5c52-315e-11e7-8f83-f0bde7737ad3.png)

EDIT: I just realized that I think I know why this is. Whenever you aren't scrolled down on a list, it cuts off the bottom portion of the list and leaves dead space there. I don't know if this is a BD feature or vanilla, but I think it should be removed in minimal mode since minimal mode is supposed to remove dead space, not add more.

**Comment by noodlebox** [comment]
This happens because of how vanilla Discord handles lazy loading of channels, server members, and emoji. It replaces the hidden items with a single block that should take up the same amount of space, but it calculates its size using the vanilla sizes of those elements. If a theme makes them smaller, Discord doesn't know that you should be able to see more of them, and so you see the empty spaces.

The only way to override that behavior requires a [very ugly hack](https://github.com/HoLLy-HaCKeR/BetterDiscord-Themes-and-Plugins/blob/master/Plugins/lazyload_patcher.md), but you could give it a try.

**Comment by Juicysteak117** [comment]
That's awesome, huge thanks for the link!

**Comment by Juicysteak117** [comment]
Though on a related note, there is also the same issue in the mutual servers tab (which seems to be unaffected by that hack you linked).

![39122fbc-4fbe-11e6-8920-c7a7076083a7](https://cloud.githubusercontent.com/assets/20595808/25768565/16d5244c-31bb-11e7-97e4-bd852b3ca09a.png)

**Comment by noodlebox** [comment]
You could try opening an issue on that project, in case anyone feels like digging into the mutual servers code too.
