### ISSUE TITLE
better discord doesnt load

### ISSUE THREAD

**Issue by FIERCEDINO080** [Jiiks/BetterDiscordApp#548]
hey guys,
i'm having this issue where better discord doesn't load. i checked and it's still installed. it doesn't show any themes, plugins, twitch emotes, or better discord settings.
anyone else experiencing this?

**Comment by FIERCEDINO080** [comment]
![image](https://user-images.githubusercontent.com/26258481/29232402-572d83c0-7ee3-11e7-9c81-6f3123529626.png)
also after reinstalling it, it just shows the loading icon in the corner and it just stays there.

**Comment by Inve1951** [comment]
it can easily take up to 20 minutes for it to finsih loading, it's very dependent on your connection
if you still got the issue please join us on the BD support server <https://discord.gg/2HScm8j>

**Comment by FIERCEDINO080** [comment]
my connection isnt the problem...now it decides to work now...
thanks for replying!

**Comment by louislitt** [comment]
The reason that discord app isn’t showing up isn’t because it hasn’t started. The app does indeed start but it is usually running the background. So, locating the app, stopping the process and restarting the app has solves the issue for a lot of users.

Here are the steps for killing the background discord process

1. Press and hold CTRL, SHIFT and Esc (CTRL + SHIFT + ESC). This should open the task manager
2. Select the Process tab
3. Scroll through the list and find the discord.exe.
4. Select the discord.exe and click End Task
 
You can also refer to other methods if you still have the issue of [Discord wont open](https://www.techwhoop.com/discord-wont-open/).

**Comment by intrnl** [comment]
are u kiddin me
