### ISSUE TITLE
Cant uninstall better discord

### ISSUE THREAD

**Issue by Diegoso01** [Jiiks/BetterDiscordApp#713]
I tried installing it but it would get stuck and never finish and now i cant launch up my discord, i looked for the folder called better discord since thats supposedly how you deleted it but i wasnt able to find any and im not sure what to do anymore any help?
Everytime i try to boot up discord this pops up and im not sure if i have to delete anything else because the betterdiscord folder isnt anywhere i looked
![image](https://user-images.githubusercontent.com/36779163/36623179-0220d4e8-18c8-11e8-9804-aa624d7ea20a.png)

**Comment by IIR2D2II** [comment]
Find the file that removes your recycle bin and restore it, I like it the same and fix it

**Comment by Diegoso01** [comment]
Im not quite sure what you mean by this you mean that i need to find a file in the recycle bin and restore it? i looked there and there wasnt anything better discord related

**Comment by Diegoso01** [comment]
Im not quite sure what you mean but i think you mean that i have to restore a file in the recycle bin but i looked there and there was nothing discord related.
Also if anyone can clarify would getting rid of better discord with an uninstaller software work?

**Comment by Diegoso01** [comment]
Also if anyone can  clarify im wondering if its possible to get rid of BetterDiscord through the use of an uninstaller such as IObit unistaller or does it have to  be manually?

**Comment by Modder4869** [comment]
@Diegoso01 use this ,https://github.com/rauenzi/BetterDiscordApp/releases , make sure Zer fork is checked

**Comment by Modder4869** [comment]
still want to remove it then , use this , just download it then run
https://gist.github.com/intrnl/09db7693fba679d78d9003d676e189c3
If you don't want to run batch then open link below 
https://github.com/Jiiks/BetterDiscordApp/wiki/Uninstalling-BD

**Comment by Diegoso01** [comment]
Ah alright thanks its working now!

**Comment by freak8** [comment]
@Modder4869 Thank you so much

**Comment by quickspare** [comment]
**Help! Help!** 
I am having the same problem except I uninstalled discord as well and now when I try to run any of the things that @Modder4869 posted it doesn't work because it can't find discord. I can't run discord, I can't uninstall discord, and I can't install discord. I have tried doing the "appdata" and "localappdata" stuff then restarting but nothing works. This is the closest thing I have found to my problem. Also, I can't even find the current discord version so I can't even do that thing where you change it from like 0.0.300 (or whatever it is) to the current discord version. **Please please please help.**

**Comment by quickspare** [comment]
@Modder4869 YOU ARE A MIRACLE WORKER I LOVE YOU PEOPLE LIKE YOU ARE WHAT THE WORLD NEEDS MORE OF OMG

**Comment by quickspare** [comment]
@Modder4869 I did the 1st link u sent but it stops loading at like extracting bandagedBD package and with details on it stops at renaming package dir
