### ISSUE TITLE
better discord settings don't show up but theme does     plz help

### ISSUE THREAD

**Issue by redpannda** [Jiiks/BetterDiscordApp#787]
<img width="1374" alt="screen shot 2018-04-28 at 9 27 05 am" src="https://user-images.githubusercontent.com/38815585/39398720-8b2221b8-4ac6-11e8-97a4-6a0651e538dc.png">

im on mac btw

**Comment by kohlercoding** [comment]
I have the same problem. Really needs to be fixed. I think a Discord update broke it.

**Comment by SylveonBottle** [comment]
Recent discord update did indeed broke this. Lots of chaos happening on the BetterDiscord2 discord. There's been no confirmed fixes, many users are recommending to do a clean install of Discord and BetterDiscord, many users say that isn't working for them. Many users suggesting something called BandageDiscord, many more users saying that did nothing but disable any themes/plugins that _were_ working. 

I heard someone say that Discord recently updated their classes. I'm going to add what I can hear, but only so I can be subscribed to this issue. There's many other issues like this one, but hopefully my contribution can put the others as a copy of this one.

When I woke up this morning, I noticed that my theme was working correctly, except user status were different than what the theme was made to do. I thought that this was due to an update to the theme, but I noticed that I was unable to check because the actual settings for BetterDiscord (and PluginRepo and ThemeRepo) buttons were completely gone. There was no "BD" logo on the bottom right, but plugins _were_ working. A lot of plugins that edited user name colors were working, and I have a plugin that re-adds the "Send" button, but it was inside of the emoji button in the text field, which was weird.

Some other plugins also weren't working correctly, but I decided that it was random, so I won't go into detail.

Then, I did the following:
1. Uninstalled Discord
2. Re-installed Discord
3. Installed BetterDiscord
4. Uninstalled Discord
5. Installed DiscordPTB
6. Installed BetterDiscordPTB
7. Uninstalled DiscordPTB
8. Re-installed Discord
9. Installed BetterDiscord

After all that was said and done, there were no changes. The same plugins would not work, and my theme was still active.

Then someone suggested I install something called BandageBetterDiscord. After the installation, all themes and plugins stopped working.

After that, I've completely removed every folder involving the word "discord" in my computer, doing a complete uninstall and removal of Discord and BetterDiscord. I've re-installed Discord, but have not installed BetterDiscord yet. I'll wait until this issue is fixed.

**Comment by master3395** [comment]
Installing BandagedBD is a working plugin/theme build.
Discord changed some lib stuff, that's why many plugins and themes broke.
I don't have info regarding what discord changed exactly

**Comment by SylveonBottle** [comment]
Just to confirm, this issue is now considered invalid due to not using the template, correct? 

Should one of us re-create it?
