### ISSUE TITLE
I can't join to any of your support servers.

### ISSUE THREAD

**Issue by T1MOXA** [Jiiks/BetterDiscordApp#840]
![image](https://user-images.githubusercontent.com/19938629/41605707-a54dcf2c-73ea-11e8-8963-2adc9918bcea.png)

**Comment by gco360** [comment]
Q: Why does this main server get a temporary outage all the time or why am i not able to join that server?
A: Discord has a builtin user limit of 5000 online users/server which then gets lifted by request. Since one of the Discord developers is nice he/she increased the limit to 7500. Unfortunately we hit that 7500 limit in just few days so now we're capped on online users again and it doesn't look like they want to increase the limit on this particular server any more(they seem to do so on any other server).
@T1MOXA

**Comment by gco360** [comment]
https://discord.gg/2HScm8j

**Comment by T1MOXA** [comment]
With the second server the same problem.

**Comment by intrnl** [comment]
[Alternative support server (for BandagedBD only)](https://discord.zackrauen.com)
