### ISSUE TITLE
your server not available 

### ISSUE THREAD

**Issue by Soheab** [Jiiks/BetterDiscordApp#843]
if accepted invite discord shows this: 
![image](https://user-images.githubusercontent.com/33902984/42056915-0aa1427c-7b1c-11e8-82b2-208a2c2059f4.png)

**Comment by intrnl** [comment]
Those two servers are usually filled with online members from time to time.
The default cap on how much users can connect to a server at once is 5k.

BetterDiscord2 has 5k member limit and the main server has 7.5k.

Since this repository is unmaintained, I'd recommend waiting for the server to go up for you, or if you prefer to post an issue instead, you should close this issue and move it to [here](https://github.com/rauenzi/BetterDiscordApp/issues/new).

**Comment by Soheab** [comment]
ah okay
